# Generated by Django 4.1.4 on 2022-12-27 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('b_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('chief_name', models.CharField(max_length=45)),
                ('address', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('type', models.CharField(max_length=45)),
                ('second_side_national_id', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('c_contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_controller.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('d_num', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('deposit_type', models.CharField(max_length=45)),
                ('interest_rate', models.FloatField()),
                ('amount', models.FloatField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_controller.branch')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('national_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('birthdate', models.DateField()),
                ('father_name', models.CharField(max_length=45)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=10)),
                ('address', models.TextField(max_length=200)),
                ('cellphone_number', models.CharField(max_length=11, unique=True)),
                ('phone_number', models.CharField(max_length=8, unique=True)),
                ('education', models.CharField(max_length=10)),
                ('marital_status', models.CharField(choices=[('m', 'married'), ('s', 'single')], max_length=10)),
                ('nationality', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('receiver_first_name', models.CharField(max_length=45)),
                ('receiver_last_name', models.CharField(max_length=45)),
                ('source_bank', models.CharField(max_length=45)),
                ('destination_bank', models.CharField(max_length=45)),
                ('destination_deposit_num', models.CharField(max_length=45)),
                ('tr_dp_num', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='main_controller.deposit')),
            ],
        ),
        migrations.CreateModel(
            name='Securities',
            fields=[
                ('security_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=45)),
                ('value', models.FloatField()),
                ('purchase_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('s_cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_controller.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('type', models.CharField(max_length=45)),
                ('interest_rate', models.FloatField()),
                ('number_of_debts', models.IntegerField()),
                ('guarantor_job', models.CharField(max_length=45)),
                ('guarantor_cnt', models.IntegerField()),
                ('l_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_controller.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('employment_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('employment_status', models.CharField(max_length=45)),
                ('job_position', models.CharField(max_length=45)),
                ('e_b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_controller.branch')),
                ('e_contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_controller.contract')),
                ('e_dp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_controller.deposit')),
                ('e_national_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_controller.personalinformation')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='c_dp_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_controller.deposit'),
        ),
        migrations.AddField(
            model_name='customer',
            name='c_national_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_controller.personalinformation'),
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('serial_num', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ch_dp_num', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='main_controller.deposit')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_num', models.IntegerField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('expire_date', models.DateField()),
                ('cvv2', models.IntegerField(unique=True)),
                ('card_dp_num', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='main_controller.deposit')),
            ],
        ),
    ]
