# Generated by Django 4.1.4 on 2022-12-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_num',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
