# Generated by Django 4.1.4 on 2022-12-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_controller', '0002_alter_card_card_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='education',
            field=models.CharField(max_length=20),
        ),
    ]
