# Generated by Django 4.1.4 on 2022-12-31 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_controller', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
    ]
